jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Шаг 3: Кэшируем зависимости
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Шаг 4: Устанавливаем зависимости и EAS CLI
      - name: Install dependencies and EAS CLI
        run: |
          npm install -g expo-cli
          npm install
          npm install -g eas-cli  # Установка eas-cli

      # Шаг 5: Проверяем переменные окружения
      - name: Verify Expo credentials
        run: |
          echo "EXPO_USERNAME is set"
          echo "EXPO_PASSWORD is set"

      # Шаг 6: Логинимся в Expo с использованием имени пользователя и пароля
      - name: Log in to Expo
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
        run: |
          expo login --username $EXPO_USERNAME --password $EXPO_PASSWORD

      # Шаг 7: Сборка проекта для Android
      - name: Build project (Android)
        run: |
          echo "Starting build for Android..."
          eas build -p android --non-interactive || echo "Build failed"
